/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CesiumViewer: typeof import('./src/components/CesiumViewer/index.vue')['default']
    Child: typeof import('./src/components/CesiumViewer/components/child.vue')['default']
    ChildComponent: typeof import('./src/components/CesiumViewer/components/child-component.vue')['default']
    EffectsView: typeof import('./src/components/CesiumViewer/components/effectsView.vue')['default']
    LeftSide: typeof import('./src/components/LeftSide/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
